# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 JWP Consulting GK

- name: Configure SSH bastion nftables
  block:
    - name: Install nftables configuration
      ansible.builtin.template:
        src: nftables.conf.j2
        dest: /etc/nftables.conf
        owner: root
        group: root
        mode: '0744'
      register: nftables_config
    - name: Reload nftables if configuration changed
      ansible.builtin.systemd:
        name: nftables
        state: reloaded
      when: nftables_config.changed

- name: Configure Prometheus
  block:
    - name: Install Prometheus and Node Exporter
      ansible.builtin.apt:
        name:
          - prometheus
          - prometheus-node-exporter
        state: present
        update_cache: yes
    - name: Configure Prometheus
      ansible.builtin.template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: "0644"
      register: prometheus_config
    - name: Configure Prometheus to listen on localhost only
      ansible.builtin.copy:
        src: prometheus-defaults
        dest: /etc/default/prometheus
        mode: "0644"
    - name: Configure Prometheus node exporter to listen on localhost only
      ansible.builtin.copy:
        src: prometheus-node-exporter-defaults
        dest: /etc/default/prometheus-node-exporter
        mode: "0644"
    - name: Enable and restart Prometheus services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: yes
        state: restarted
        daemon_reload: yes
      loop:
        - prometheus
        - prometheus-node-exporter
      when: prometheus_config.changed
    - name: Reload Prometheus if config changed
      ansible.builtin.systemd:
        name: prometheus
        state: reloaded
      when: prometheus_config.changed

- name: Configure Grafana
  block:
    # See
    # https://grafana.com/docs/grafana/latest/setup-grafana/installation/debian/
    - name: Install required packages for Grafana
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - wget
          - gnupg
        state: present
        update_cache: yes
    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
    - name: Download Grafana GPG key
      ansible.builtin.get_url:
        url: https://apt.grafana.com/gpg-full.key
        dest: /etc/apt/keyrings/grafana.asc
        mode: "0644"
    - name: Add Grafana repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main"
        state: present
        filename: grafana
    - name: Install Grafana
      ansible.builtin.apt:
        name: grafana
        state: present
        update_cache: yes
    - name: Ensure Grafana directory exists
      ansible.builtin.file:
        path: /usr/share/grafana
        state: directory
        owner: grafana
        group: grafana
        mode: "0700"
    - name: Configure Grafana
      ansible.builtin.template:
        src: grafana.ini.j2
        dest: /etc/grafana/grafana.ini
        owner: grafana
        group: grafana
        mode: "0644"
      register: grafana_config
    - name: Configure Grafana datasource
      ansible.builtin.template:
        src: datasource.yml.j2
        dest: /etc/grafana/provisioning/datasources/prometheus.yml
        owner: grafana
        group: grafana
        mode: "0644"
      register: grafana_datasource
    - name: Enable and start Grafana service
      ansible.builtin.systemd:
        name: grafana-server
        enabled: yes
        state: started
    - name: Restart Grafana if configuration changed
      ansible.builtin.systemd:
        name: grafana-server
        state: restarted
      when: grafana_config.changed or grafana_datasource.changed
