import type { ThemeColors } from "$lib/types";

export const factoryLightThemeColors: ThemeColors = {
    "primary": "#288CFF",
    "primary-focus": "#0077FF",
    "primary-content": "#ffffff",
    "secondary": "#BEDCFF",
    "secondary-focus": "#76B4F9",
    "secondary-content": "#ffffff",
    "accent": "#EF7D69",
    "accent-focus": "#F05F46",
    "accent-content": "#ffffff",
    "neutral": "#3578C0",
    "neutral-focus": "#5399E4",
    "neutral-content": "#ffffff",
    "base-100": "#ffffff",
    "base-200": "#F2F8FF",
    "base-300": "#d1d5db",
    "base-content": "#1f2937",
    "info": "#2094f3",
    "success": "#009485",
    "warning": "#ff9900",
    "error": "#ff5724",
};

export const factoryDarkThemeColors: ThemeColors = {
    "primary": "#4db2fe",
    "primary-focus": "#0077FF",
    "primary-content": "#ffffff",
    "secondary": "#5ca3ff",
    "secondary-focus": "#76B4F9",
    "secondary-content": "#ffffff",
    "accent": "#EF7D69",
    "accent-focus": "#F05F46",
    "accent-content": "#ffffff",
    "neutral": "#5B5AA0",
    "neutral-focus": "#7F7ED3",
    "neutral-content": "#ffffff",
    "base-100": "#282841",
    "base-200": "#191e32",
    "base-300": "#3c3c5a",
    "base-content": "#ffffff",
    "info": "#2094f3",
    "success": "#009485",
    "warning": "#ff9900",
    "error": "#ff5724",
};
