# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) 2021, 2023 JWP Consulting GK
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Add timestamps to workspace models."""
# Generated by Django 4.0 on 2021-12-15 06:52

import datetime
from datetime import (
    timezone,
)

from django.db import (
    migrations,
)

import django_extensions.db.fields


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0003_workspaceboard"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workspace",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="workspaceboard",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="workspaceuser",
            options={"get_latest_by": "modified"},
        ),
        migrations.AddField(
            model_name="workspace",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2021, 12, 15, 6, 52, 28, 779635, tzinfo=timezone.utc
                ),
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workspace",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="workspaceboard",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2021, 12, 15, 6, 52, 32, 996331, tzinfo=timezone.utc
                ),
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workspaceboard",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="workspaceuser",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2021, 12, 15, 6, 52, 37, 906080, tzinfo=timezone.utc
                ),
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workspaceuser",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
