# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) 2022, 2023 JWP Consulting GK
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Unique Constraint for Order on Workspace Board Section and Task."""
# Generated by Django 3.2.12 on 2022-03-17 01:15

from typing import (
    TYPE_CHECKING,
    cast,
)

from django.apps.registry import (
    Apps,
)
from django.db import (
    migrations,
)

if TYPE_CHECKING:
    from workspace.models import WorkspaceBoard as _WorkspaceBoard


def ensure_correct_order(apps: Apps, schema_editor: object) -> None:
    """Correct _order field."""
    WorkspaceBoard = cast(
        "_WorkspaceBoard", apps.get_model("workspace", "WorkspaceBoard")
    )
    for workspaceboard in WorkspaceBoard.objects.all():
        for i, wbs in enumerate(
            workspaceboard.workspaceboardsection_set.all()
        ):
            wbs._order = i
            wbs.save()
            workspaceboard.save()

            for i, task in enumerate(wbs.task_set.all()):
                task._order = i
                task.save()
                wbs.save()


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0027_auto_20220317_0115"),
    ]

    operations = [
        migrations.RunPython(ensure_correct_order),
    ]
