# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2022, 2023, 2026 JWP Consulting GK
"""Formerly: Ensure SubTask _order is unique."""
# Generated by Django 4.0.2 on 2022-05-31 04:27

from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0031_alter_subtask_options_and_more"),
    ]

    operations = []
