# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) 2022, 2023 JWP Consulting GK
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Populate assignee_workspace_user field."""
# Generated by Django 4.0.4 on 2022-06-29 07:42
from typing import (
    TYPE_CHECKING,
    cast,
)

from django.apps.registry import (
    Apps,
)
from django.db import (
    migrations,
)

if TYPE_CHECKING:
    from workspace.models import Task as _Task


def add_assignee_workspace_user_to_task(
    apps: Apps, schema_editor: object
) -> None:
    """Populate assignee_workspace_user field in tasks."""
    Task = cast("_Task", apps.get_model("workspace", "Task"))
    WorkspaceUser = apps.get_model("workspace", "WorkspaceUser")
    for task in Task.objects.all():
        try:
            ws_user = WorkspaceUser.objects.get(
                workspace=task.workspace,
                user=task.assignee,
            )
        except WorkspaceUser.DoesNotExist:
            ws_user = None
        task.assignee_workspace_user = ws_user  # type: ignore
        task.save()


class Migration(migrations.Migration):
    """Migrations."""

    dependencies = [
        ("workspace", "0042_task_assignee_workspace_user"),
    ]

    operations = [migrations.RunPython(add_assignee_workspace_user_to_task)]
