# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2022, 2023 JWP Consulting GK
"""Empty migration."""

# Generated by Django 4.0.4 on 2022-06-29 07:42

from django.db import migrations


class Migration(migrations.Migration):
    """Migrations."""

    dependencies = [
        ("workspace", "0042_task_assignee_workspace_user"),
    ]

    operations = []
