# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2022 JWP Consulting GK
"""Remove assignee from task."""
# Generated by Django 4.0.4 on 2022-06-29 14:09

from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0043_auto_20220629_0742"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assignee",
        ),
    ]
