# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2022, 2023 JWP Consulting GK
"""Empty migration."""
# Generated by Django 4.0.4 on 2022-06-30 04:28

from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0046_chatmessage_author_workspace_user"),
    ]

    operations = []
