# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) 2023 JWP Consulting GK
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Use different enum for role."""
# Generated by Django 4.0.4 on 2022-07-12 07:24

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0049_rename_author_workspace_user_chatmessage_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("OBSERVER", "Observer"),
                    ("MEMBER", "Member"),
                    ("MAINTAINER", "Maintainer"),
                    ("OWNER", "Owner"),
                ],
                default="OBSERVER",
                max_length=10,
            ),
        ),
    ]
