# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 JWP Consulting GK
# Generated by Django 4.2.7 on 2024-01-10 06:43
"""Empty migration."""

from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0052_alter_workspaceboard_options"),
    ]

    operations = []
