# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 JWP Consulting GK
# Generated by Django 4.2.7 on 2024-01-13 00:04
"""Rename deadline -> due date."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0053_task_read_only_task_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="deadline",
            new_name="due_date",
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                blank=True, help_text="Due date for this task", null=True
            ),
        ),
    ]
