# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 JWP Consulting GK
# Generated by Django 4.2.7 on 2024-02-08 02:53
"""Alter Label model to be ordered by modified DESC."""

from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0055_rename_deadline_workspaceboard_due_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="label",
            options={"ordering": ("-modified",)},
        ),
    ]
