# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 JWP Consulting GK
"""Annotate ws user invite with redeemd_when dt field."""
# Generated by Django 4.2.7 on 2024-02-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0056_alter_label_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceuserinvite",
            name="redeemed_when",
            field=models.DateTimeField(
                blank=True,
                default=None,
                editable=False,
                help_text="When has this invite been redeemed?",
                null=True,
            ),
        ),
    ]
