# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 JWP Consulting GK
"""Rename model WorkspaceBoardSection -> Section."""

# Generated by Django 4.2.10 on 2024-03-15 10:08
from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0057_workspaceuserinvite_redeemed_when"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkspaceBoardSection",
            new_name="Section",
        ),
    ]
