# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 JWP Consulting GK
"""Rename WorkspaceBoard -> Project."""

# Generated by Django 4.2.10 on 2024-03-15 15:21
import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0058_rename_workspaceboardsection_section_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkspaceBoard",
            new_name="Project",
        ),
        migrations.RemoveConstraint(
            model_name="section",
            name="unique_workspace_board_order",
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("workspace_board", "_order"),
                name="unique_project_order",
            ),
        ),
    ]
