# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 JWP Consulting GK
"""Rename member role to contributor."""

# Generated by Django 4.2.10 on 2024-03-17 10:27
from typing import Any

from django.apps.registry import Apps
from django.db import migrations, models


def rename_member_to_contributor(apps: Apps, schema_editor: object) -> None:
    """Migrate all existing MEMBER roles to be CONTRIBUTOR instead."""
    WorkspaceUser: Any = apps.get_model("workspace", "WorkspaceUser")
    qs = WorkspaceUser.objects.filter(role="MEMBER")
    qs.update(role="CONTRIBUTOR")


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0059_rename_workspaceboard_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("OBSERVER", "Observer"),
                    ("CONTRIBUTOR", "Contributor"),
                    ("MAINTAINER", "Maintainer"),
                    ("OWNER", "Owner"),
                ],
                default="OBSERVER",
                max_length=11,
            ),
        ),
        migrations.RunPython(rename_member_to_contributor),
    ]
