# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 JWP Consulting GK
# Generated by Django 5.0.3 on 2024-04-08 06:23
"""Rename Task.workspace_board_section -> section."""

import django.db.models.constraints
from django.db import migrations, models

import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    """
    Migration with workaround.

    Use a temporary field as order with respect to, to work around bug
    involving renamefield/alterorderwithrespectto colliding.
    """

    dependencies = [
        ("workspace", "0061_rename_workspaceuser_teammember_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="task",
            name="unique_task_order",
        ),
        migrations.AlterOrderWithRespectTo(
            name="task",
            order_with_respect_to="uuid",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="task",
            name="ensure_correct_workspace",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="workspace_board_section",
            new_name="section",
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("section", "_order"),
                name="unique_task_order",
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="task",
            order_with_respect_to="section",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="task",
            trigger=pgtrigger.compiler.Trigger(
                name="ensure_correct_workspace",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='\n                      DECLARE\n                        correct_workspace_id   INTEGER;\n                      BEGIN\n                        SELECT "workspace_workspace"."id" INTO correct_workspace_id\n                        FROM "workspace_workspace"\n                        INNER JOIN "workspace_project"\n                            ON ("workspace_workspace"."id" =                             "workspace_project"."workspace_id")\n                        INNER JOIN "workspace_section"\n                            ON ("workspace_project"."id" =                                  "workspace_section"."workspace_board_id")\n                        INNER JOIN "workspace_task"\n                            ON ("workspace_section"."id" =                                 "workspace_task"."section_id")\n                        WHERE "workspace_task"."id" = NEW.id\n                        LIMIT 1;\n                        IF correct_workspace_id != NEW.workspace_id THEN\n                            RAISE EXCEPTION \'invalid workspace_id: workspace being                                 inserted does not match correct derived workspace.\';\n                        END IF;\n                        RETURN NEW;\n                      END;',
                    hash="45aa3dce09be3502e9ab1142fd87d6609eaaf174",
                    operation="INSERT OR UPDATE",
                    pgid="pgtrigger_ensure_correct_workspace_b7606",
                    table="workspace_task",
                    when="BEFORE",
                ),
            ),
        ),
    ]
