# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 JWP Consulting GK
# Generated by Django 5.0.3 on 2024-04-08 06:23
"""Rename Task.workspace_board_section -> section."""

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration with workaround.

    Use a temporary field as order with respect to, to work around bug
    involving renamefield/alterorderwithrespectto colliding.
    """

    dependencies = [
        ("workspace", "0061_rename_workspaceuser_teammember_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="task",
            name="unique_task_order",
        ),
        migrations.AlterOrderWithRespectTo(
            name="task",
            order_with_respect_to="uuid",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="workspace_board_section",
            new_name="section",
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("section", "_order"),
                name="unique_task_order",
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="task",
            order_with_respect_to="section",
        ),
    ]
