# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 JWP Consulting GK
"""Rename workspace board -> project in Section."""

# Generated by Django 5.0.3 on 2024-04-08 06:32
import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Implement the same workaround as the previous migration.

    Rename order with respect to field temporarily, then turn back into
    section.
    """

    dependencies = [
        ("workspace", "0062_remove_task_unique_task_order_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="section",
            name="unique_project_order",
        ),
        migrations.AlterOrderWithRespectTo(
            name="section",
            order_with_respect_to="uuid",
        ),
        migrations.RenameField(
            model_name="section",
            old_name="workspace_board",
            new_name="project",
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("project", "_order"),
                name="unique_project_order",
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="section",
            order_with_respect_to="project",
        ),
    ]
