# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2023-2024 JWP Consulting GK
"""Change workspace title to not allow for url like strings."""
# Generated by Django 5.0.3 on 2024-04-09 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0064_alter_label_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                # type: ignore[call-arg]
                condition=models.Q(
                    ("title__regex", "^([.:]\\s|[^.:])*[.:]?$")
                ),
                name="title",
                violation_error_message="Workspace title can only contain '.' or ':' if followed by whitespace or if located at the end.",
            ),
        ),
    ]
