# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Add section minimization."""
# Generated by Django 5.2.9 on 2026-01-28 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """The migration."""

    dependencies = [
        ("workspace", "0067_alter_workspace_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="minimized_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have minimized this section",
                related_name="minimized_sections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
