# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Add user preferences to team member model."""
# Generated by Django 5.2.9 on 2026-02-08 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0068_section_minimized_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="last_visited_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Last project visited by this team member in this workspace",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workspace.project",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="last_visited_workspace",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when this team member last visited this workspace",
                null=True,
            ),
        ),
    ]
