# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Explicitly order team members and their invites."""
# Generated by Django 6.0.2 on 2026-02-28 13:42

from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0072_alter_label_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammember",
            options={"ordering": ("created",)},
        ),
        migrations.AlterModelOptions(
            name="teammemberinvite",
            options={"ordering": ("created",)},
        ),
    ]
