# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Remove task numbering."""
# Generated by Django 6.0.2 on 2026-03-01 05:16

from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0073_alter_teammember_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="task",
            name="unique_task_number",
        ),
        migrations.RemoveField(
            model_name="workspace",
            name="highest_task_number",
        ),
        migrations.RemoveField(
            model_name="task",
            name="number",
        ),
    ]
