# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Add done field to tasks."""
# Generated by Django 6.0.2 on 2026-03-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0074_remove_task_unique_task_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="done",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
