# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Remove ensure_correct_workspace trigger from Task model."""
# Generated by Django 6.0.3 on 2026-03-27 12:12

from django.db import migrations

import pgtrigger.migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0075_task_done"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="task",
            name="ensure_correct_workspace",
        ),
    ]
