# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Empty migration."""
# Generated by Django 6.0.3 on 2026-03-27 12:12

from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0075_task_done"),
    ]

    operations = []
