# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Alter task description to be rich text field."""
# Generated by Django 6.0.3 on 2026-04-06 01:41

from django.db import migrations

import projectify.lib.models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [("workspace", "0076_auto_20260327_1212")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=projectify.lib.models.RichTextField(
                blank=True, null=True, verbose_name="description"
            ),
        )
    ]
