# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
# Generated by Django 6.0.4 on 2026-04-16 12:51
"""Remove SubTask model."""

from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [("workspace", "0077_alter_task_description")]

    operations = [
        migrations.RemoveConstraint(
            model_name="subtask", name="unique_sub_task_order"
        ),
        migrations.DeleteModel(name="SubTask"),
    ]
