# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
# Generated by Django 6.0.4 on 2026-04-21 14:38
"""Remove task ordering."""

from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        (
            "workspace",
            "0078_remove_subtask_unique_sub_task_order_delete_subtask",
        )
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task", options={"ordering": ("done", "-modified")}
        ),
        migrations.RemoveConstraint(
            model_name="task", name="unique_task_order"
        ),
        migrations.AlterOrderWithRespectTo(
            name="task",
            order_with_respect_to=None,  # type: ignore[arg-type]
        ),
    ]
