# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Remove ChatMessage model."""
# Generated by Django 6.0.4 on 2026-05-02 00:41

from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        (
            "workspace",
            "0079_alter_task_options_remove_task_unique_task_order_and_more",
        )
    ]

    operations = [migrations.DeleteModel(name="ChatMessage")]
