# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Delete Label and TaskLabel model."""
# Generated by Django 6.0.4 on 2026-05-02 00:54

from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [("workspace", "0080_delete_chatmessage")]

    operations = [
        migrations.RemoveConstraint(
            model_name="label", name="label_color_range"
        ),
        migrations.RemoveConstraint(
            model_name="label", name="unique_label_name_per_workspace"
        ),
        migrations.RemoveField(model_name="task", name="labels"),
        migrations.RemoveField(
            model_name="teammember", name="minimized_label_filter"
        ),
        migrations.RemoveField(model_name="label", name="workspace"),
        migrations.DeleteModel(name="TaskLabel"),
        migrations.DeleteModel(name="Label"),
    ]
