# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Remove sections. Map tasks to projects directly."""
# Generated by Django 6.0.4 on 2026-05-02 11:48

from typing import Any

import django.db.migrations.operations.special
import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models


def set_task_project_from_section(apps: Apps, schema_editor: object) -> None:
    """Set task.project based on task.section.project."""
    del schema_editor
    Task: Any = apps.get_model("workspace", "Task")
    for task in Task.objects.select_related("section__project").iterator():
        task.project = task.section.project
        task.save(update_fields=["project"])


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0081_remove_label_label_color_range_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workspace.project",
            ),
        ),
        migrations.RunPython(
            code=set_task_project_from_section,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(model_name="task", name="section"),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="workspace.project",
            ),
        ),
    ]
