# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Order tasks by done is NULL first."""
# Generated by Django 6.0.4 on 2026-05-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [("workspace", "0082_remove_sections")]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": [
                    models.OrderBy(models.F("done"), nulls_first=True),
                    models.OrderBy(models.F("modified"), descending=True),
                ]
            },
        )
    ]
