# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Remove section model."""
# Generated by Django 6.0.4 on 2026-05-08 10:30

from django.db import migrations

import projectify.lib.models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [("workspace", "0083_alter_task_options")]

    operations = [
        migrations.RemoveConstraint(
            model_name="section", name="unique_project_order"
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=projectify.lib.models.RichTextField(
                blank=True, null=True, verbose_name="description"
            ),
        ),
        migrations.DeleteModel(name="Section"),
    ]
