# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Remove minimized fields."""
# Generated by Django 6.0.4 on 2026-05-08 10:33

from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0084_remove_section_unique_project_order_and_more")
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember", name="minimized_project_list"
        ),
        migrations.RemoveField(
            model_name="teammember", name="minimized_team_member_filter"
        ),
    ]
