# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Create Attachment model."""
# Generated by Django 6.0.5 on 2026-07-02 09:03

import django.db.models.deletion
from django.db import migrations, models

import projectify.lib.models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0085_remove_teammember_minimized_project_list_and_more")
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    projectify.lib.models.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    projectify.lib.models.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Attachment file name",
                        max_length=512,
                        unique=True,
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        help_text="Attachment size in bytes"
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workspace.teammember",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.workspace",
                    ),
                ),
            ],
        )
    ]
