# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Create Wiki page model."""
# Generated by Django 6.0.5 on 2026-07-02 11:08

import uuid

import django.db.models.deletion
from django.db import migrations, models

import projectify.lib.models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [("workspace", "0086_attachment")]

    operations = [
        migrations.CreateModel(
            name="WikiPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    projectify.lib.models.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    projectify.lib.models.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="Wiki page title",
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                (
                    "content",
                    projectify.lib.models.RichTextField(
                        blank=True, null=True, verbose_name="content"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={"unique_together": {("title", "workspace")}},
        )
    ]
