* Features

** Localstore remember
   Remember with sidenav menus have been open and not in localstorage

** DONE Date picker
   Evaluate [[https://www.npmjs.com/package/date-picker-svelte][this]] as date
   picker.
   CLOSED: [2023-08-03 Thu 11:36]

** Due dates
   Show that due dates are stored as UTC+0

** Deadline -> Due date
    Due date sounds less threatening

** Full name -> Preferred name
   <2023-08-03 Thu>
   We want to respect how a user wants to be called.

   Asking them to provide a full name even if they don't want to be called that
   way reeks of social media real name policies that only serve large
   corporations and their need to moderate what they deem are undesirable
   opinions. Word. Make things personal and respectful.

* Unfinished

** Reintegrate mobile menu overlay as proper overlay (whatever that means)

* Bug

** Step count is not shown during onboarding
   Justus <2023-08-02>

** Header height difference
   Solve issue where all headers have different heights (at least on Desktop)

** Buttons inside flex
   Fix issue where buttons don't react well when placed inside an items-center
   flex with column layout

** dashboard/task/uuid does not support refetching
   Is this still a bug? Justus <2023-05-01>

** Overlay form submit
   Add new workspace board section overlay does not react well when pressing
   enter.
   Justus <2023-05-01>

** Sub task progress wrong
   In the task card on the dashboard, the sub task progress is falsely shown as
   100 % for tasks with no sub tasks.
   Justus <2023-05-01>

** Clicking cancel doesn't do anything in the constructive overlays

** It would be nice to show login after attempting to fetch user

** Fix storybook svelte kit goto import issue

* Refactor

** TODO Change OverlayContainer to accept overlay as slto
   <2023-08-27 Sun>
   This is more sveltonic?

** Tertiary nav btns to be replaced by HeaderButton

** Update button to use ButtonAction

** Use async in overlays
   All overlays should use async functions so we can await them finishing /
   closing / whatever it is that they do

** Consistent undefined
   Make undefined and null for empty form fields more consistent. We want to
   use undefined all the time. [[Check this][https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#null-and-undefined]].

   The only time where null makes sense is when asking for an object from an
   API/DB and nothing could be found. [[See
   here][https://stackoverflow.com/questions/5076944/what-is-the-difference-between-null-and-undefined-in-javascript/57249968#57249968]].

** Refactor ButtonAction
   Factor disabled state into ButtonAction (since anchors cannot be disabled)

** Remove store modules
   Reintroduce calling the store from lib/figma components instead of module
   construct

** Better business object stores
  Create a store factory for self-refreshing task / ws / ws board entities,
   then

  1. Perform initial load in page ts, so that a page can definitely be rendered
     with a entity instance,
  2. Continuously reassign $entity to page data so it stays fresh.

** A label should have title/description, not name

** Rename /onboarding/assign-task
   It would be better if we named this something like
   ~/onboarding/finished/[taskUuid]~

* Update Dependency

** Update [cite/t:@steeze-ui/heroicons]
   Some of the icons have been renamed (search, eye, ...)

* QA

** Consider introducing shellcheck

** Warn about unused variables (possible just in svelte files)

* DONE The drop down in user assignment does not indicate the current
  assignee
