"""Whitelist for vulture. Not currently used for testing."""
# ruff: noqa: F821
app_name  # unused variable (workspace/urls.py:11)
constraints  # unused variable (workspace/models.py:967)
django_get_or_create  # unused variable (user/factory.py:37)
extra  # unused variable (workspace/admin.py:23)
format  # unused variable (workspace/views/workspace.py:114)
inlines  # unused variable (workspace/admin.py:92)
list_display  # unused variable (workspace/admin.py:93)
list_select_related  # unused variable (workspace/admin.py:99)
lookup_field  # unused variable (blog/views.py:34)
order_with_respect_to  # unused variable (workspace/models.py:966)
ordering  # unused variable (workspace/models.py:1022)
parser_classes  # unused variable (workspace/views/workspace.py:108)
published  # unused variable (blog/models.py:40)
read_only_fields  # unused variable (workspace/serializers/base.py:122)
readonly_fields  # unused variable (workspace/admin.py:37)
serializer_class  # unused variable (workspace/views/workspace.py:90)
unique_together  # unused variable (workspace/models.py:892)
