# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2021, 2023 JWP Consulting GK
"""Add unconfirmed_email field and track user's previous email addresses."""
# Generated by Django 4.2.7 on 2024-02-14 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import projectify.lib.models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("user", "0012_rename_full_name_user_preferred_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="unconfirmed_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="If update email address requested, new, unconfirmed email",
            ),
        ),
        migrations.CreateModel(
            name="PreviousEmailAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    projectify.lib.models.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    projectify.lib.models.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Previous email address", max_length=254
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this email address belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
