# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Track user activation date."""
# Generated by Django 6.0.5 on 2026-07-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("user", "0017_alter_user_is_active_alter_user_is_staff_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activated",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time user account was activated",
                null=True,
                editable=False,
                verbose_name="Activated",
            ),
        )
    ]
