# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Add UserEvent model."""
# Generated by Django 6.0.5 on 2026-07-22 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import projectify.lib.models


class Migration(migrations.Migration):
    """Run migration."""

    dependencies = [("user", "0018_user_activated")]

    operations = [
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    projectify.lib.models.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    projectify.lib.models.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SIGN_UP", "sign up"),
                            ("CONFIRM_EMAIL", "confirm email"),
                            ("LOG_IN", "log in"),
                            ("LOG_OUT", "log out"),
                            ("REQUEST_PW_RESET", "request password reset"),
                            ("CONFIRM_PW_RESET", "confirm password reset"),
                            ("UPDATE_PROFILE", "update profile"),
                            ("SET_PW", "set password"),
                            ("CHANGE_PW", "change password"),
                            ("REQUEST_EMAIL_UPDATE", "request email update"),
                            ("CONFIRM_EMAIL_UPDATE", "confirm email update"),
                        ]
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"get_latest_by": "modified", "abstract": False},
        )
    ]
