# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) 2021 JWP Consulting GK
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Create workspace board section."""
# Generated by Django 4.0 on 2021-12-16 03:34

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)

import django_extensions.db.fields


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        (
            "workspace",
            "0005_alter_workspace_options_alter_"
            "workspaceboard_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceBoardSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="description"
                    ),
                ),
                (
                    "workspace_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workspace.workspaceboard",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
