# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) 2022, 2023 JWP Consulting GK
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Populate chat message author_workspace_user field."""
# Generated by Django 4.0.4 on 2022-06-30 04:28

from typing import (
    TYPE_CHECKING,
    cast,
)

from django.apps.registry import (
    Apps,
)
from django.db import (
    migrations,
)

if TYPE_CHECKING:
    from projectify.workspace.models import ChatMessage as _ChatMessage
    from projectify.workspace.models import WorkspaceUser as _WorkspaceUser


def add_author_workspace_user_to_chat_message(
    apps: Apps, schema_editor: object
) -> None:
    """Populate author_workspace_user field in chat messages."""
    ChatMessage = cast(
        "_ChatMessage", apps.get_model("workspace", "ChatMessage")
    )
    WorkspaceUser = cast(
        "_WorkspaceUser", apps.get_model("workspace", "WorkspaceUser")
    )
    for chat_message in ChatMessage.objects.all():
        try:
            ws_user = WorkspaceUser.objects.get(
                workspace=chat_message.task.workspace,
                user=chat_message.author,
            )
        except WorkspaceUser.DoesNotExist:
            ws_user = None
        chat_message.author_workspace_user = ws_user  # type: ignore
        chat_message.save()


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0046_chatmessage_author_workspace_user"),
    ]

    operations = [
        migrations.RunPython(add_author_workspace_user_to_chat_message),
    ]
