# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2021-2024 JWP Consulting GK
# Generated by Django 4.2.7 on 2024-01-13 00:12
"""Rename workspace board deadline -> due date."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0054_rename_deadline_task_due_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workspaceboard",
            old_name="deadline",
            new_name="due_date",
        ),
        migrations.AlterField(
            model_name="workspaceboard",
            name="due_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Due date for this workspace board",
                null=True,
            ),
        ),
    ]
