# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) 2024 JWP Consulting GK
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Annotate ws user invite with redeemd_when dt field."""
# Generated by Django 4.2.7 on 2024-02-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0056_alter_label_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceuserinvite",
            name="redeemed_when",
            field=models.DateTimeField(
                blank=True,
                default=None,
                editable=False,
                help_text="When has this invite been redeemed?",
                null=True,
            ),
        ),
    ]
