# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) 2024 JWP Consulting GK
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Rename member role to contributor."""

# Generated by Django 4.2.10 on 2024-03-17 10:27
from typing import Any

from django.apps.registry import Apps
from django.db import migrations, models


def rename_member_to_contributor(apps: Apps, schema_editor: object) -> None:
    """Migrate all existing MEMBER roles to be CONTRIBUTOR instead."""
    WorkspaceUser: Any = apps.get_model("workspace", "WorkspaceUser")
    qs = WorkspaceUser.objects.filter(role="MEMBER")
    qs.update(role="CONTRIBUTOR")


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0059_rename_workspaceboard_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("OBSERVER", "Observer"),
                    ("CONTRIBUTOR", "Contributor"),
                    ("MAINTAINER", "Maintainer"),
                    ("OWNER", "Owner"),
                ],
                default="OBSERVER",
                max_length=11,
            ),
        ),
        migrations.RunPython(rename_member_to_contributor),
    ]
