# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 JWP Consulting GK
"""Make label color field required."""
# Generated by Django 5.0.3 on 2024-05-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0063_alter_section_order_with_respect_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="color",
            field=models.PositiveBigIntegerField(help_text="Color index"),
        ),
    ]
