# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2025 JWP Consulting GK
# Generated by Django 5.2.9 on 2026-01-26 07:17
"""Validate label color range."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """The migration."""

    dependencies = [
        ("workspace", "0065_workspace_title"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="label",
            constraint=models.CheckConstraint(
                # type: ignore[call-arg]
                condition=models.Q(("color__gte", 0), ("color__lte", 7)),
                name="label_color_range",
                violation_error_message="Color must be between 0 and 7",
            ),
        ),
    ]
