# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Update users field on workspace."""
# Generated by Django 5.2.9 on 2026-01-28 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """The migration."""

    dependencies = [
        ("workspace", "0066_alter_workspace_users_label_label_color_range"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="users",
            field=models.ManyToManyField(
                through="workspace.TeamMember",
                through_fields=("workspace", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
