"""Turn unique_together into UniqueConstraint."""
# Generated by Django 5.2.11 on 2026-02-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0071_teammember_minimized_filters"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="label",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.UniqueConstraint(
                fields=("name", "workspace"),
                name="unique_label_name_per_workspace",
                violation_error_message="You can only create one label with this name.",
            ),
        ),
    ]
