# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2021 JWP Consulting GK
"""Mark users as inactive by default."""
# Generated by Django 4.0 on 2021-12-09 01:09

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("user", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Is active"),
        ),
    ]
