# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) 2023 JWP Consulting GK
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# Generated by Django 4.2.7 on 2023-12-25 05:07
"""Store in user whether tos / privacy policy have been agreed to."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add two datetime fields."""

    dependencies = [
        ("user", "0009_userinvite_redeemed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="privacy_policy_agreed",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time user has agreed to privacy policy",
                null=True,
                verbose_name="Privacy Policy agreed",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tos_agreed",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time user has agreed to terms of service",
                null=True,
                verbose_name="Terms of service agreed",
            ),
        ),
    ]
