# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 JWP Consulting GK
# Generated by Django 4.2.7 on 2024-01-13 00:47
"""Rename full_name -> preferred_name."""

from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("user", "0011_alter_user_options_user_created_user_modified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="full_name",
            new_name="preferred_name",
        ),
    ]
