# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 JWP Consulting GK
# Generated by Django 5.0.3 on 2024-04-05 08:13
"""Add check constraint to restrict possible User preferred names."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0013_user_unconfirmed_email_previousemailaddress"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("preferred_name__regex", "^([.:]\\s|[^.:])+$")
                ),
                name="preferred_name",
                violation_error_message="Preferred name can only contain '.' or ':' if followed by whitespace.",
            ),
        ),
    ]
