# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 JWP Consulting GK
# Generated by Django 5.0.3 on 2024-06-10 01:52
"""Allow empty string for user preferred name."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0015_remove_user_preferred_name_user_preferred_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="preferred_name",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("preferred_name__regex", "^([.:]\\s|[^.:])*[.:]?$")
                ),
                name="preferred_name",
                violation_error_message="Preferred name can only contain '.' or ':' if followed by whitespace or if located at the end.",
            ),
        ),
    ]
