"""Use different enum for subscription_status."""
# Generated by Django 4.0.4 on 2022-07-12 07:24

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("corporate", "0003_alter_customer_subscription_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("UNPAID", "Unpaid"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="UNPAID",
                max_length=9,
            ),
        ),
    ]
