"""Add CUSTOM tier to subscription."""
# Generated by Django 4.2.7 on 2023-12-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    """Perform migration."""

    dependencies = [
        ("corporate", "0004_alter_customer_subscription_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("UNPAID", "Unpaid"),
                    ("CANCELLED", "Cancelled"),
                    ("CUSTOM", "Custom subscription"),
                ],
                default="UNPAID",
                max_length=9,
            ),
        ),
    ]
