# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 JWP Consulting GK

- name: "Verify that backup storage {{ backup_storage_path }} is mounted at /srv/backups"
  ansible.builtin.command:
      cmd: "findmnt --source '{{ backup_storage_path }}' --mountpoint /srv/backups"
  changed_when: false
  register: findmnt_result
  failed_when: findmnt_result.rc != 0

- name: Install dependencies for Projectify app server
  ansible.builtin.apt:
      name:
          # db, postgresql
          - postgresql
          - postgresql-contrib
          - pgbackrest
          # For community.postgresql.postgresql_db
          - python3-psycopg2
          # venv creation for Projectify source code
          - python3-virtualenv
          # Compile psycopg-c, see
          # https://www.psycopg.org/psycopg3/docs/basic/install.html#local-installation
          - libpq-dev
          - build-essential
          - python3-dev
          # Back up media
          - rsync
          # Rev proxy
          - caddy
          # Used to check out projectify repo
          - git
          # Monitoring
          - prometheus-node-exporter
      state: present

- name: Configure projectify user
  block:
    - name: Create projectify user
      ansible.builtin.user:
          name: projectify
          group: projectify
          system: true
          shell: /bin/bash
          home: "{{ projectify_user_home }}"
          create_home: true
    - name: Create releases root directory
      ansible.builtin.file:
          path: "{{ projectify_releases_root }}"
          state: directory
          owner: projectify
          group: projectify
          mode: '0755'

- name: Configure Prometheus Node Exporter on app server
  block:
    - name: Configure node exporter to listen on private network
      ansible.builtin.copy:
        src: prometheus-node-exporter-defaults
        dest: /etc/default/prometheus-node-exporter
        mode: "0644"
      register: node_exporter_config

    - name: Enable and restart node exporter
      ansible.builtin.systemd:
        name: prometheus-node-exporter
        enabled: yes
        state: restarted
      when: node_exporter_config.changed

- name: Configure nftables for app server
  block:
    - name: Install nftables configuration
      ansible.builtin.template:
          src: nftables.conf.j2
          dest: /etc/nftables.conf
          owner: root
          group: root
          mode: '0744'
      register: nftables_config
    - name: Reload nftables if configuration changed
      ansible.builtin.systemd:
          name: nftables
          state: reloaded
      when: nftables_config.changed

- name: Configure PostgreSQL
  block:
    - name: Install postgresql main configuration
      ansible.builtin.template:
        src: postgresql.conf
        dest: "/etc/postgresql/17/main/postgresql.conf"
        mode: '0644'
        owner: root
        group: root
      register: postgresql_conf
    - name: Reload PostgreSQL
      ansible.builtin.systemd:
          name: postgresql
          enabled: true
          state: reloaded
      when: postgresql_conf.changed
    - name: Create projectify database user
      community.postgresql.postgresql_user:
          name: projectify
          login_db: projectify
      become: true
      become_user: postgres
    - name: Create projectify database
      community.postgresql.postgresql_db:
          name: projectify
          owner: projectify
      become: true
      become_user: postgres
    - name: Check whether projectify user can log into projectify database
      ansible.builtin.command:
          cmd: psql -U projectify -d projectify -c "SELECT 1"
      become: true
      become_user: projectify

- name: Configure pgBackRest
  block:
    - name: Create pgBackRest directories
      ansible.builtin.file:
          path: "{{ item }}"
          state: directory
          owner: postgres
          group: postgres
          mode: '0750'
      loop:
          # Expect volume mounted at /srv/backups
          - "{{ pgbackrest_dest }}"
          - /var/log/pgbackrest
    - name: Install pgBackRest configuration
      ansible.builtin.template:
          src: pgbackrest.conf.j2
          dest: /etc/pgbackrest.conf
          owner: root
          group: root
          mode: '0644'
    - name: Create pgBackRest stanza
      ansible.builtin.command:
          cmd: pgbackrest --stanza=projectify stanza-create
      args:
        creates: "{{ pgbackrest_dest }}/backup/projectify"
      become: true
      become_user: postgres
    - name: Check pbBackRest configuration
      ansible.builtin.command:
          cmd: pgbackrest --stanza=projectify --log-level-console=info check
      become: true
      become_user: postgres

- name: Configure pgBackRest backup services
  block:
    - name: Copy pgBackRest backup systemd units
      ansible.builtin.template:
          src: "{{ item }}.j2"
          dest: "/etc/systemd/system/{{ item  }}"
          owner: root
          group: root
          mode: '0644'
      loop:
          - pgbackrest-full.service
          - pgbackrest-full.timer
          - pgbackrest-diff.service
          - pgbackrest-diff.timer
      register: pgbackrest_units
    - name: Reload systemd daemon
      ansible.builtin.systemd:
          daemon_reload: true
      when: pgbackrest_units.changed
    - name: Enable and start pgBackRest full backup timer
      ansible.builtin.systemd:
          name: pgbackrest-full.timer
          enabled: true
          state: started
    - name: Enable and start pgBackRest differential backup timer
      ansible.builtin.systemd:
          name: pgbackrest-diff.timer
          enabled: true
          state: started

- name: Configure media backup rsync service
  block:
    - name: Create state root directory
      ansible.builtin.file:
          path: "{{ state_root }}"
          state: directory
          owner: projectify
          group: caddy
          mode: '0750'
    - name: Create media directory
      ansible.builtin.file:
          path: "{{ media_root }}"
          state: directory
          owner: projectify
          group: caddy
          mode: '0750'
    - name: Create media backup directory
      ansible.builtin.file:
          path: "{{ media_backup_dest }}"
          state: directory
          owner: projectify
          group: projectify
          mode: '0700'
    - name: Copy media backup systemd service unit
      ansible.builtin.template:
          src: projectify-media-backup.service.j2
          dest: /etc/systemd/system/projectify-media-backup.service
          owner: root
          group: root
          mode: '0644'
      register: media_backup_service
    - name: Copy media backup systemd timer unit
      ansible.builtin.template:
          src: projectify-media-backup.timer.j2
          dest: /etc/systemd/system/projectify-media-backup.timer
          owner: root
          group: root
          mode: '0644'
      register: media_backup_timer
    - name: Reload systemd daemon
      ansible.builtin.systemd:
          daemon_reload: true
      when: media_backup_service.changed or media_backup_timer.changed
    - name: Enable and start media backup timer
      ansible.builtin.systemd:
          name: projectify-media-backup.timer
          enabled: true
          state: started
  tags:
    - media

- name: Checkout and build Projectify release
  block:
    - name: Clone Projectify repository to temporary location
      ansible.builtin.git:
          repo: https://github.com/jwpconsulting/projectify.git
          dest: /tmp/projectify_clone
          version: main
          depth: 1
      register: git_clone
    - name: Set release directory name
      ansible.builtin.set_fact:
          release_dir: "{{ projectify_releases_root }}/{{ ansible_date_time.date }}_{{ git_clone.after[:7] }}"
    - name: Check if release already exists
      ansible.builtin.stat:
          path: "{{ release_dir }}"
      register: release_exists
    - name: Create release directory
      ansible.builtin.file:
          path: "{{ release_dir }}"
          state: directory
          owner: projectify
          group: projectify
          mode: '0755'
      when: not release_exists.stat.exists
    - name: Move cloned repository to release directory
      ansible.builtin.command:
          cmd: "mv /tmp/projectify_clone {{ release_dir }}/app"
      when: not release_exists.stat.exists
    - name: Create virtual environment and upgrade pip in venv
      ansible.builtin.pip:
          name: pip
          state: latest
          virtualenv: "{{ release_dir }}/venv"
      when: not release_exists.stat.exists
    - name: Install Python dependencies from requirements.txt
      ansible.builtin.pip:
          requirements: "{{ release_dir }}/app/requirements.txt"
          virtualenv: "{{ release_dir }}/venv"
      when: not release_exists.stat.exists
    - name: Run collectstatic
      ansible.builtin.command:
          cmd: "{{ release_dir }}/venv/bin/python ./manage.py collectstatic --noinput"
          chdir: "{{ release_dir }}/app"
      environment:
          DJANGO_SETTINGS_MODULE: projectify.settings.collect_static
          DJANGO_CONFIGURATION: CollectStatic
          STATIC_ROOT: "{{ release_dir }}/static"
      when: not release_exists.stat.exists
    - name: Create symbolic link for current release
      ansible.builtin.file:
          src: "{{ release_dir }}"
          dest: "{{ projectify_current_release }}"
          state: link
          owner: projectify
          group: projectify
          force: yes
  become: true
  become_user: projectify
  tags:
    - gunicorn

- name: Configure gunicorn
  block:
    - name: Create gunicorn config directory
      ansible.builtin.file:
          path: "{{ gunicorn_config_file | ansible.builtin.dirname }}"
          state: directory
          owner: root
          group: root
          mode: '0755'
    - name: Copy gunicorn configuration files
      ansible.builtin.template:
          src: "{{ item.src }}"
          dest: "{{ item.dest}}"
          owner: root
          group: root
          mode: '0644'
      loop:
          - src: gunicorn.socket.j2
            dest: /etc/systemd/system/gunicorn.socket
          - src: gunicorn.service.j2
            dest: /etc/systemd/system/gunicorn.service
          - src: gunicorn.conf.py.j2
            dest: "{{ gunicorn_config_file }}"
          - src: gunicorn-error.log.j2
            dest: "{{ gunicorn_log_config_file }}"
      register: gunicorn_config_files
    - name: "Verify gunicorn credentials file {{ credentials_file }} exists"
      ansible.builtin.stat:
          path: "{{ credentials_file }}"
      register: credentials_file_stat
      failed_when: not credentials_file_stat.stat.exists
    - name: Reload systemd daemon if gunicorn files changed
      ansible.builtin.systemd:
          daemon_reload: true
      when: gunicorn_config_files.changed
    - name: Enable and start gunicorn socket
      ansible.builtin.systemd:
          name: gunicorn.socket
          enabled: true
          state: started
      when: gunicorn_config_files.changed
    - name: Enable and reload gunicorn service
      ansible.builtin.systemd:
          name: gunicorn.service
          enabled: true
          state: reloaded
      when: gunicorn_config_files.changed
    - name: Restart gunicorn service after app release
      ansible.builtin.systemd:
          name: gunicorn.service
          enabled: true
          state: restarted
      # Run only when creating new release
      when: not release_exists.stat.exists
    - name: Check gunicorn health
      ansible.builtin.command:
          cmd: curl --unix-socket /run/gunicorn.sock {{ hostname }}
      become: true
      become_user: caddy
  tags:
      - gunicorn

- name: Configure Caddy
  block:
    - name: Copy Caddyfile
      ansible.builtin.template:
          src: Caddyfile.j2
          dest: /etc/caddy/Caddyfile
          owner: root
          group: root
          mode: '0644'
      register: caddyfile
    - name: Reload caddy service if Caddyfile changed
      ansible.builtin.systemd:
          name: caddy
          state: reloaded
      when: caddyfile.changed
    - name: Enable and start caddy service
      ansible.builtin.systemd:
          name: caddy
          enabled: true
          state: started
    - name: Check caddy health
      ansible.builtin.command:
          cmd: curl https://{{ hostname }}
  tags:
    - caddy
