# Generated by Django 3.2.7 on 2021-09-24 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todo", "0003_auto_20210923_1517"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitemfolder",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
            ),
            preserve_default=False,
        ),
    ]
