# Generated by Django 3.2.7 on 2021-09-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_todoitemfolder_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="done",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
