# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Create index to speed up daily count aggregation."""
# Generated by Django 6.0.7 on 2026-07-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [("stats", "0001_initial")]

    operations = [
        migrations.AddIndex(
            model_name="dailycount",
            index=models.Index(
                fields=["date", "name"], name="stats_dailycount_date_and_name"
            ),
        )
    ]
