from typing import Any

class WebsocketCommunicator:
    scope: dict[str, Any]

    def __init__(self, asgi_application: object, resource: str) -> None: ...

    # connected, subprotocol
    async def connect(self) -> tuple[bool, object]: ...
    async def disconnect(self) -> None: ...
    async def receive_json_from(self) -> object: ...
    async def receive_nothing(self) -> bool: ...

    # From agiref.testing.ApplicationCommuniactor.receive_output
    async def receive_output(self, timeout: int = 1) -> dict[str, Any]: ...
