# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2021-2024 JWP Consulting GK
"""
Django settings for projectify project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
import warnings
from collections.abc import Sequence
from pathlib import Path
from typing import Any, Optional

from django.utils.csp import CSP  # type: ignore
from django.utils.log import DEFAULT_LOGGING

import dj_database_url

from configurations import Configuration  # type: ignore

from .monkeypatch import patch
from .types import (
    SocialAccountProvider,
    StoragesConfig,
    StripeConfig,
    TemplatesConfig,
)


def environ_get_or_warn(
    key: str, comment: Optional[str] = None
) -> Optional[str]:
    """Get an environment variable or warn that it is not set."""
    value = os.environ.get(key)

    if value is not None:
        return value

    warnings.warn(
        f"{key} needed for settings was not set in environment.\n{comment}"
    )
    return None


patch()


class Base(Configuration):  # type:ignore
    """
    Base configuration.

    Largely derived from Django quick-start development settings - unsuitable
    for production.

    See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/
    """

    SECRET_KEY: str

    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent.parent

    # Used in admin site to show which environment we are using
    SITE_TITLE: Optional[str] = None

    # SECURITY WARNING: don't run with debug turned on in production!
    ALLOWED_HOSTS: Sequence[str] = []

    # Debug
    # Should Django run in debug mode?
    DEBUG = False
    # Should Projectify render the Django debug toolbar?
    DEBUG_TOOLBAR = False
    # Should Projectify make authentication debug views available?
    DEBUG_AUTH = False
    # Do we let users see error pages directly?
    DEBUG_ERROR_PAGES = False

    # Frontend URL configuration
    # --------------------------
    # This is used to create full URLs for emails
    # In production, this points to the Svelte frontend. As soon as the Svelte
    # frontend is gone, the new Django backend is available on the same
    # hostname and port. This value doesn't need to be changed in production
    # It's set to None by default to catch potential configuration errors.
    FRONTEND_URL: Optional[str] = None

    SESSION_COOKIE_SAMESITE = "Strict"
    SESSION_COOKIE_SECURE = True

    # CSRF
    # Don't store CSRF cookies in session, for now.
    # This increases many query count checks in tests by 4 queries.
    # For reference, here's what you'd have to pay attention to if you enable
    # CSRF_USE_SESSIONS = True
    # > Since the default error views require the CSRF token, SessionMiddleware must appear in MIDDLEWARE before any middleware that may raise an exception to trigger an error view (such as PermissionDenied) if you’re using CSRF_USE_SESSIONS. See Middleware ordering.
    # See
    # https://docs.djangoproject.com/en/6.0/ref/settings/#std-setting-CSRF_USE_SESSIONS
    # Note: Set to False now because it increases the query count
    CSRF_USE_SESSIONS = False
    CSRF_COOKIE_SAMESITE = "Strict"
    CSRF_COOKIE_SECURE = True
    # > Although the setting offers little practical benefit, it’s sometimes required by security auditors.
    # https://docs.djangoproject.com/en/6.0/ref/settings/#csrf-cookie-httponly
    CSRF_COOKIE_HTTPONLY = True

    # HSTS
    # Approximately one year
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # CSP
    # https://docs.djangoproject.com/en/6.0/ref/settings/#secure-csp
    SECURE_CSP: dict[str, Any] = {
        "default-src": [CSP.SELF, CSP.NONCE],
        "script-src": [CSP.SELF, CSP.NONCE],
        "font-src": [CSP.SELF],
        "style-src": [CSP.SELF, CSP.NONCE],
        "img-src": [CSP.SELF],
        "form-action": [
            CSP.SELF,
            "https://github.com",
            "https://accounts.google.com",
        ],
        "connect-src": [CSP.SELF],
        "frame-ancestors": [CSP.NONE],
        "object-src": [CSP.NONE],
        "frame-src": [CSP.NONE],
        "base-uri": [CSP.NONE],
    }

    # Installed applications
    # Applications from Django project
    INSTALLED_APPS_DJANGO = (
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.sitemaps",
        "django.contrib.staticfiles",
    )

    # Any third party applications we are using
    # It's wise to reduce our dependency on third party dependencies as much as
    # we can, while avoiding to reinvent the wheel every time.
    INSTALLED_APPS_THIRD_PARTY = (
        "rules.apps.AutodiscoverRulesConfig",
        "markdownify.apps.MarkdownifyConfig",
        # Allauth
        "allauth",
        "allauth.account",
        # Optional -- requires install using `django-allauth[socialaccount]`.
        "allauth.socialaccount",
        "allauth.socialaccount.providers.github",
        "allauth.socialaccount.providers.google",
    )

    INSTALLED_APPS_FIRST_PARTY = (
        "projectify",
        # XXX django.forms is added here so that we have a chance to override
        # templates
        "django.forms",
        # TODO check if this can be alphabetized
        # Replaces 'django.contrib.admin'
        "projectify.admin.apps.ProjectifyAdminConfig",
        "projectify.blog",
        "projectify.corporate.apps.CorporateConfig",
        "projectify.premail",
        "projectify.stats",
        "projectify.storefront",
        "projectify.help",
        "projectify.onboarding",
        "projectify.user.apps.UserConfig",
        "projectify.workspace.apps.WorkspaceConfig",
        "projectify.theme",
    )

    INSTALLED_APPS: Sequence[str] = (
        INSTALLED_APPS_DJANGO
        # Install first party apps first
        # This lets us override allauth templates
        + INSTALLED_APPS_FIRST_PARTY
        + INSTALLED_APPS_THIRD_PARTY
    )

    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "django.middleware.csp.ContentSecurityPolicyMiddleware",
        "projectify.middleware.reverse_proxy",
        "django.middleware.gzip.GZipMiddleware",
        # SessionMiddleware
        # Before any middleware that may raise an exception to trigger an error view (such as PermissionDenied) if you’re using CSRF_USE_SESSIONS.
        # https://docs.djangoproject.com/en/6.0/ref/middleware/#middleware-ordering
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        # CsrfViewMiddleware
        # After SessionMiddleware if you’re using CSRF_USE_SESSIONS.
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        "projectify.lib.htmx.HtmxMiddleware",
        "allauth.account.middleware.AccountMiddleware",
        "projectify.stats.middleware.count_stats",
    ]

    ROOT_URLCONF = "projectify.urls"

    WSGI_APPLICATION = "projectify.wsgi.application"

    # Database
    # https://docs.djangoproject.com/en/3.2/ref/settings/#databases
    DATABASES: dict[str, dj_database_url.DBConfig]
    CONN_MAX_AGE = 0

    # Django authentication settings
    # ==============================
    AUTHENTICATION_BACKENDS = (
        "rules.permissions.ObjectPermissionBackend",
        "django.contrib.auth.backends.ModelBackend",
    )
    AUTH_USER_MODEL = "user.User"
    LOGIN_URL = "/user/log-in"

    # Password validation
    # https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        },
        {
            "NAME": "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        },
        {
            "NAME": "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        },
        {
            "NAME": "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        },
    ]

    # Django-allauth
    # ==============
    ACCOUNT_USER_MODEL_USERNAME_FIELD = None
    ACCOUNT_SIGNUP_FIELDS = [
        "email*",
        "password1*",
        "password2*",
        "tos_agreed*",
        "privacy_policy_agreed*",
    ]
    ACCOUNT_LOGIN_METHODS = {"email"}
    LOGIN_REDIRECT_URL = "/user/profile"
    ACCOUNT_SIGNUP_REDIRECT_URL = "/onboarding"
    ACCOUNT_EMAIL_VERIFICATION = "none"

    # django allauth social account settings
    # --------------------------
    SOCIALACCOUNT_ONLY = True
    SOCIALACCOUNT_AUTO_SIGNUP = False
    SOCIALACCOUNT_EMAIL_AUTHENTICATION = False
    SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = False
    SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
    SOCIALACCOUNT_FORMS = {
        "signup": "projectify.user.forms.SocialAccountSignUpForm"
    }
    # Provider specific settings
    SOCIALACCOUNT_PROVIDERS: dict[str, SocialAccountProvider] = {
        # See `docs/auth.md` under **Edit GitHub OAuth settings**
        "github": {
            "SCOPE": ["user:email"],
            # TODO add django configuration check for these variables
            # TODO disable GH log in route if no APPS are set
            "APPS": [],
        },
        # See `docs/auth.md` under **Edit Google OAuth settings**
        "google": {
            "SCOPE": ["email"],
            # TODO add django configuration check for these variables
            # TODO disable GH log in route if these env vars are not
            # given
            "APPS": [],
        },
    }

    # Internationalization
    # https://docs.djangoproject.com/en/3.2/topics/i18n/
    LANGUAGE_CODE = "en-us"

    TIME_ZONE = "UTC"

    USE_I18N = True

    USE_TZ = True

    # Picture asset restrictions
    # ==========================
    # Blog
    # ----
    # These are the names as returned by Pillow.Image.open().format
    BLOG_ALLOWED_FILE_TYPES = {"PNG", "JPEG"}
    # 1 MiB
    BLOG_ALLOWED_FILE_SIZE = 1 * 1024 * 1024
    # User pictures
    USER_PROFILE_PICTURE_FILE_TYPES = {"PNG", "JPEG"}
    # 1 MiB
    USER_PROFILE_PICTURE_FILE_SIZE = 1 * 1024 * 1024
    # Workspace pictures
    WORKSPACE_PICTURE_FILE_TYPES = {"PNG", "JPEG"}
    # 1 MiB
    WORKSPACE_PICTURE_FILE_SIZE = 1 * 1024 * 1024

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/3.2/howto/static-files/
    STATIC_URL = "/static/django/"
    STATIC_ROOT = BASE_DIR / "staticfiles"

    # Where to store media
    MEDIA_ROOT = BASE_DIR / "media"
    MEDIA_URL = "/media/"
    # This configures whether ./manage.py runserver should serve media files
    # ONLY use this for debugging or local development
    SENDFILE_BACKEND: Optional[str] = None
    SENDFILE_ROOT: Path

    STORAGES: StoragesConfig = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
        },
    }
    # https://github.com/openwisp/django-minify-compress-staticfiles?tab=readme-ov-file#settings
    # Allow compressing minified files
    MINICOMPRESS_EXCLUDE_PATTERNS = ["*.gz", "*.br", "*.zip"]

    # Default primary key field type
    # https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
    DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

    TEMPLATES: TemplatesConfig = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": (
                    "projectify.context_processors.frontend_url",
                    "django.template.context_processors.csp",
                    "django.template.context_processors.debug",
                    # `allauth` needs this from django
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                )
            },
        }
    ]
    FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

    # Email
    DEFAULT_FROM_EMAIL: str = '"Projectify" <hello@projectifyapp.com>'
    # Prefix for admin emails, see
    # https://docs.djangoproject.com/en/6.0/ref/settings/#email-subject-prefix
    EMAIL_SUBJECT_PREFIX = "[Projectify-Admin] "

    # Logging
    LOGGING: Any = {
        **DEFAULT_LOGGING,
        "formatters": {
            **DEFAULT_LOGGING["formatters"],
            "like_gunicorn": {
                "format": "%(levelname)-s [%(name)s.%(module)s] ~ %(message)s"
            },
        },
        "handlers": {
            **DEFAULT_LOGGING["handlers"],
            "console": {
                **DEFAULT_LOGGING["handlers"]["console"],
                "formatter": "like_gunicorn",
            },
        },
        "loggers": {
            **DEFAULT_LOGGING["loggers"],
            "django": {
                **DEFAULT_LOGGING["loggers"]["django"],
                "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            },
            "projectify": {
                "handlers": ["console", "mail_admins"],
                "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            },
        },
    }
    # https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-ADMINS
    # > Each item in the list should be a tuple of (Full name, email address). Example:
    ADMINS: list[list[str]] = []

    # Stripe
    STRIPE_CONFIG: Optional[StripeConfig] = None

    # django-ratelimit
    RATELIMIT_ENABLE = True

    # premail
    PREMAIL_PREVIEW = False

    # https://github.com/adamchainz/django-browser-reload
    BROWSER_RELOAD = False

    # Markdownify
    MARKDOWNIFY = {
        "default": {
            "WHITELIST_ATTRS": ["href", "src", "alt", "id"],
            "WHITELIST_TAGS": [
                "a",
                # Blocks
                "blockquote",
                "div",
                "p",
                # Formatting
                "em",
                "strong",
                "sup",
                "br",
                "span",
                # images
                "figure",
                "figcaption",
                "img",
                # Lists
                "ul",
                "li",
                "ol",
                # Headings
                "h1",
                "h2",
                "h3",
                # Code
                "pre",
                "code",
                # HTML 5 things
                "abbr",
                "acronym",
                # Table things
                "table",
                "thead",
                "th",
                "td",
                "tr",
            ],
            "LINKIFY_TEXT": {"PARSE_URLS": False},
            "MARKDOWN_EXTENSIONS": [
                "markdown.extensions.fenced_code",
                "markdown.extensions.footnotes",
                "markdown.extensions.tables",
                "markdown.extensions.toc",
            ],
        }
    }

    @classmethod
    def setup(cls) -> None:
        """Load database config, after environment is correctly loaded."""
        cls.DATABASES = {
            "default": dj_database_url.config(conn_max_age=cls.CONN_MAX_AGE)
        }
        cls.SENDFILE_ROOT = cls.MEDIA_ROOT

    @classmethod
    def post_setup(cls) -> None:
        """Warn if configuration variables not set correctly."""
        # Technically, this won't catch multiple trailing slashes... but who
        # would specify a URL like that?
        if cls.FRONTEND_URL is None:
            warnings.warn(
                "FRONTEND_URL is not set. This might cause template rendering to break"
            )
        elif cls.FRONTEND_URL.endswith("/"):
            warnings.warn("Please ensure FRONTEND_URL does not end on a '/'")
            cls.FRONTEND_URL = cls.FRONTEND_URL[:-1]

        if cls.SENDFILE_BACKEND is None:
            warnings.warn("Must specify SENDFILE_BACKEND")
