# SPDX-FileCopyrightText: 2024 JWP Consulting GK
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Initialize nix docker build
inputs:
    build_target:
        required: true
    package_name:
        required: true
    username:
        required: true
    password:
        required: true
runs:
    using: "composite"
    steps:
        - uses: DeterminateSystems/nix-installer-action@v12
        - uses: DeterminateSystems/magic-nix-cache-action@v7
        - uses: DeterminateSystems/flake-checker-action@v8
        - name: Build image streamer
          run: nix build --out-link result.bash ${{ inputs.build_target }}
          shell: bash
        - name: Authenticate with skopeo if main branch
          run: nix run .#skopeo -- login --username=${{ inputs.username }} --password='${{ inputs.password }}' ghcr.io
          shell: bash
          if: ${{ github.ref_name == 'main' }}
        - name: Push with skopeo if main branch
          run: bash result.bash | nix run .#skopeo -- copy docker-archive:/dev/stdin docker://ghcr.io/${{ github.repository }}/${{ inputs.package_name }}
          shell: bash
          if: ${{ github.ref_name == 'main' }}
