# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Add blog post back."""
# Generated by Django 6.0.3 on 2026-03-27 02:36

import django.db.models.deletion
from django.db import migrations, models

import projectify.blog.models
import projectify.lib.models


class Migration(migrations.Migration):
    """Migration."""

    initial = True

    dependencies = [
        ("blog", "0002_remove_postimage_post_delete_post_delete_postimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", projectify.blog.models.DocumentContentField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    projectify.lib.models.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    projectify.lib.models.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(verbose_name="Blog post title")),
                (
                    "slug",
                    models.SlugField(
                        verbose_name="Blog post slug",
                        unique=True,
                        max_length=255,
                    ),
                ),
                (
                    "published",
                    models.DateTimeField(
                        verbose_name="Blog post publish date"
                    ),
                ),
                (
                    "body",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.postcontent",
                        verbose_name="Blog post body",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
