# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Add author field to blog posts."""
# Generated by Django 6.0.3 on 2026-03-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("blog", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(
                default="", verbose_name="Blog post author"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateField(verbose_name="Blog post publish date"),
        ),
    ]
