# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Sort posts by published in descending order."""
# Generated by Django 6.0.3 on 2026-03-27 09:04

from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("blog", "0004_post_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"get_latest_by": "modified", "ordering": ["-published"]},
        ),
    ]
