# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 JWP Consulting GK
"""Add published field."""
# Generated by Django 6.0.4 on 2026-04-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [("blog", "0005_alter_post_options")]

    operations = [
        migrations.AddField(
            model_name="post",
            name="draft",
            field=models.BooleanField(
                default=False, verbose_name="Blog post draft status"
            ),
        )
    ]
