class WebsocketCommunicator:
    scope: dict[str, object]

    def __init__(self, asgi_application: object, resource: str) -> None: ...

    # connected, subprotocol
    async def connect(self) -> tuple[bool, object]: ...
    async def disconnect(self) -> None: ...
    async def receive_json_from(self) -> object: ...
