"""Create Workspace model."""
# Generated by Django 4.0 on 2021-12-14 13:44

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
