"""Add workspace board."""
# Generated by Django 4.0 on 2021-12-15 06:49

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0002_workspaceuser_workspace_users_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workspace.workspace",
                    ),
                ),
            ],
        ),
    ]
