"""Create workspace board section."""
# Generated by Django 4.0 on 2021-12-16 03:34

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)

import django_extensions.db.fields


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        (
            "workspace",
            "0005_alter_workspace_options_alter_"
            "workspaceboard_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceBoardSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="description"
                    ),
                ),
                (
                    "workspace_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workspace.workspaceboard",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
