"""Add ordering to workspace board section."""
# Generated by Django 4.0 on 2021-12-16 04:23

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0006_workspaceboardsection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workspaceboardsection",
            options={"ordering": ("workspace_board", "order")},
        ),
        migrations.AddField(
            model_name="workspaceboardsection",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
