"""
Add done field to SubTask. Change ChatMessage ordering.

The latter was accidentally forgotten and sneaked in.
"""
# Generated by Django 3.2.11 on 2022-01-28 10:34

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0011_chatmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ("created",)},
        ),
        migrations.AddField(
            model_name="subtask",
            name="done",
            field=models.BooleanField(
                default=False,
                help_text="Designate whether this sub task is done",
            ),
        ),
    ]
