# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) 2022 JWP Consulting GK
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Ensure a workspace user can't be created twice."""
# Generated by Django 3.2.11 on 2022-02-08 05:09

from django.conf import (
    settings,
)
from django.db import (
    migrations,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspace", "0013_task_assignee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workspaceuser",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="workspaceuser",
            unique_together={("workspace", "user")},
        ),
    ]
