"""Ensure a workspace user can't be created twice."""
# Generated by Django 3.2.11 on 2022-02-08 05:09

from django.conf import (
    settings,
)
from django.db import (
    migrations,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspace", "0013_task_assignee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workspaceuser",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="workspaceuser",
            unique_together={("workspace", "user")},
        ),
    ]
