"""Add archived field to workspace board."""
# Generated by Django 3.2.11 on 2022-02-15 04:44

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0014_auto_20220208_0509"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceboard",
            name="archived",
            field=models.DateTimeField(
                blank=True,
                help_text="Archival timestamp of this workspace board.",
                null=True,
            ),
        ),
    ]
