"""Add deadline to task."""
# Generated by Django 3.2.11 on 2022-02-15 08:35

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0015_workspaceboard_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                blank=True, help_text="Task's deadline", null=True
            ),
        ),
    ]
