"""Implement Order on Task and WorkSpaceBoardSection."""

# Generated by Django 3.2.12 on 2022-03-02 01:06

from django.db import (
    migrations,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0016_task_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
        migrations.AlterModelOptions(
            name="workspaceboardsection",
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name="task",
            order_with_respect_to="workspace_board_section",
        ),
        migrations.AlterOrderWithRespectTo(
            name="workspaceboardsection",
            order_with_respect_to="workspace_board",
        ),
        migrations.RemoveField(
            model_name="task",
            name="order",
        ),
        migrations.RemoveField(
            model_name="workspaceboardsection",
            name="order",
        ),
    ]
