"""Add deadline to workspace."""
# Generated by Django 4.0.2 on 2022-03-04 03:47

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0017_workspace_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceboard",
            name="deadline",
            field=models.DateTimeField(
                blank=True, help_text="Workspace board's deadline", null=True
            ),
        ),
    ]
