"""Allow cascading delete for task."""
# Generated by Django 4.0.2 on 2022-03-04 04:03

import django.db.models.deletion
from django.conf import (
    settings,
)
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspace", "0018_workspaceboard_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="workspace.task",
            ),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="workspace.task",
            ),
        ),
    ]
