"""Allow cascading workspace board delete."""
# Generated by Django 4.0.2 on 2022-03-04 04:16

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0020_alter_task_workspace_board_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceboardsection",
            name="workspace_board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="workspace.workspaceboard",
            ),
        ),
    ]
