"""Add redeemed flag to invites."""
# Generated by Django 4.0.2 on 2022-03-09 08:35

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0024_workspaceuserinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceuserinvite",
            name="redeemed",
            field=models.BooleanField(
                default=False, help_text="Has this invite been redeemed?"
            ),
        ),
    ]
