"""Allow delete of user when workspaceuser is present."""
# Generated by Django 4.0.2 on 2022-03-09 08:43

import django.db.models.deletion
from django.conf import (
    settings,
)
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspace", "0025_workspaceuserinvite_redeemed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
