"""Unique Constraint for Order on Workspace Board Section and Task."""
# Generated by Django 3.2.12 on 2022-03-17 01:15

import django.db.models.constraints
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0026_alter_workspaceuser_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
        migrations.AlterModelOptions(
            name="workspaceboardsection",
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name="task",
            order_with_respect_to="workspace_board_section",
        ),
        migrations.AlterOrderWithRespectTo(
            name="workspaceboardsection",
            order_with_respect_to="workspace_board",
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("workspace_board_section", "_order"),
                name="unique_task_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspaceboardsection",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("workspace_board", "_order"),
                name="unique_workspace_board_order",
            ),
        ),
        migrations.RemoveField(
            model_name="task",
            name="order",
        ),
        migrations.RemoveField(
            model_name="workspaceboardsection",
            name="order",
        ),
    ]
