"""Unique Constraint for Order on Workspace Board Section and Task."""
# Generated by Django 3.2.12 on 2022-03-17 01:15

from django.db import (
    migrations,
)


def ensure_correct_order(apps, schema_editor):
    """Correct _order field."""
    WorkspaceBoard = apps.get_model("workspace", "WorkspaceBoard")
    for workspaceboard in WorkspaceBoard.objects.all():
        for i, wbs in enumerate(
            workspaceboard.workspaceboardsection_set.all()
        ):

            wbs._order = i
            wbs.save()
            workspaceboard.save()

            for i, task in enumerate(wbs.task_set.all()):
                task._order = i
                task.save()
                wbs.save()


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0027_auto_20220317_0115"),
    ]

    operations = [
        migrations.RunPython(ensure_correct_order),
    ]
