"""Add unique order constraint to SubTask _order."""
# Generated by Django 4.0.2 on 2022-05-31 04:27

import django.db.models.constraints
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0032_auto_20220531_0427"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subtask",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("task", "_order"),
                name="unique_sub_task_order",
            ),
        ),
    ]
