"""Make task.number non-nullable."""
# Generated by Django 4.0.4 on 2022-06-18 05:46

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0036"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="number",
            field=models.PositiveIntegerField(),
        ),
    ]
