"""Make task.workspace non-nullable."""
# Generated by Django 4.0.4 on 2022-06-18 05:47

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0037_alter_task_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="workspace.workspace",
            ),
        ),
    ]
