"""Add role field to workspace user."""
# Generated by Django 4.0.4 on 2022-06-18 03:27

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0038_alter_task_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("OBSE", "Observer"),
                    ("MEMB", "Member"),
                    ("MAIN", "Maintainer"),
                    ("OWNE", "Owner"),
                ],
                default="OBSE",
                max_length=4,
            ),
        ),
    ]
