"""Add job title to workspace user."""
# Generated by Django 4.0.4 on 2022-06-20 12:11

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0039_workspaceuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceuser",
            name="job_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
