"""Add workspace user assignee to task."""
# Generated by Django 4.0.4 on 2022-06-29 06:59

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0041_alter_chatmessage_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assignee_workspace_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace user this task is assigned to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workspace.workspaceuser",
            ),
        ),
    ]
