"""Populate assignee_workspace_user field."""
# Generated by Django 4.0.4 on 2022-06-29 07:42
from typing import (
    TYPE_CHECKING,
    cast,
)

from django.apps.registry import (
    Apps,
)
from django.db import (
    migrations,
)

if TYPE_CHECKING:
    from workspace.models import Task as _Task


def add_assignee_workspace_user_to_task(
    apps: Apps, schema_editor: object
) -> None:
    """Populate assignee_workspace_user field in tasks."""
    Task = cast("_Task", apps.get_model("workspace", "Task"))
    WorkspaceUser = apps.get_model("workspace", "WorkspaceUser")
    for task in Task.objects.all():
        try:
            ws_user = WorkspaceUser.objects.get(
                workspace=task.workspace,
                user=task.assignee,
            )
        except WorkspaceUser.DoesNotExist:
            ws_user = None
        task.assignee_workspace_user = ws_user  # type: ignore
        task.save()


class Migration(migrations.Migration):
    """Migrations."""

    dependencies = [
        ("workspace", "0042_task_assignee_workspace_user"),
    ]

    operations = [migrations.RunPython(add_assignee_workspace_user_to_task)]
