"""Rename chat message author field."""
# Generated by Django 4.0.4 on 2022-06-30 07:02

from django.db import (
    migrations,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0048_remove_chatmessage_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="author_workspace_user",
            new_name="author",
        ),
    ]
