"""Use different enum for role."""
# Generated by Django 4.0.4 on 2022-07-12 07:24

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("workspace", "0049_rename_author_workspace_user_chatmessage_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("OBSERVER", "Observer"),
                    ("MEMBER", "Member"),
                    ("MAINTAINER", "Maintainer"),
                    ("OWNER", "Owner"),
                ],
                default="OBSERVER",
                max_length=10,
            ),
        ),
    ]
