# Generated by Django 4.2.7 on 2024-01-09 01:08
"""Order workspace boards by most recently created."""

from django.db import migrations


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        (
            "workspace",
            "0051_label_created_label_modified_tasklabel_created_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workspaceboard",
            options={"ordering": ("-created",)},
        ),
    ]
