# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2026 JWP Consulting GK

- name: Configure SSH Bastion
  hosts: ssh_bastion
  roles:
    - system
    - ssh_bastion

- name: Configure Projectify App Server
  hosts: projectify_app
  roles:
    - system
    - projectify_app
  vars:
    projectify_releases_root: /usr/share/projectify/releases
    projectify_current_release: "{{ projectify_releases_root }}/current"
    app_root: "{{ projectify_current_release }}/app"
    static_root: "{{ projectify_current_release }}/static"
    venv_path: "{{ projectify_current_release }}/venv"
    projectify_user_home: /var/lib/projectify
    state_root: /var/lib/projectify-state
    media_root: "{{ state_root }}/media"
    # Expect volume mounted at /srv/backups
    media_backup_dest: /srv/backups/projectify_app_media
    pgbackrest_dest: /srv/backups/pgbackrest
    credentials_file: "{{ projectify_user_home }}/credentials.toml"
    hostname: www.projectifyapp.com
    gunicorn_config_file: /etc/gunicorn/gunicorn.conf.py
    gunicorn_log_config_file: /etc/gunicorn/gunicorn-error.log
