"""Alter user email."""
# Generated by Django 4.0 on 2021-12-09 01:08

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("user", "0003_auto_20210924_0753"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email"
            ),
        ),
    ]
