# Generated by Django 4.2.7 on 2023-12-25 05:07
"""Store in user whether tos / privacy policy have been agreed to."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add two datetime fields."""

    dependencies = [
        ("user", "0009_userinvite_redeemed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="privacy_policy_agreed",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time user has agreed to privacy policy",
                null=True,
                verbose_name="Privacy Policy agreed",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tos_agreed",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time user has agreed to terms of service",
                null=True,
                verbose_name="Terms of service agreed",
            ),
        ),
    ]
