# Generated by Django 4.2.7 on 2023-12-25 05:13
"""Make User a BaseModel."""

import django.utils.timezone
from django.db import migrations

import django_extensions.db.fields


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ("user", "0010_user_privacy_policy_agreed_user_tos_agreed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"get_latest_by": "modified"},
        ),
        migrations.AddField(
            model_name="user",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
