# SPDX-FileCopyrightText: 2024 JWP Consulting GK
#
# SPDX-License-Identifier: AGPL-3.0-or-later

class BaseParser: ...
class JSONParser: ...
class FormParser: ...
class MultiPartParser: ...
class FileUploadParser: ...
